@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=E:\CV-analyzer-light - test 1\node_modules\.pnpm\drizzle-kit@0.30.6\node_modules\drizzle-kit\node_modules;E:\CV-analyzer-light - test 1\node_modules\.pnpm\drizzle-kit@0.30.6\node_modules;E:\CV-analyzer-light - test 1\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=E:\CV-analyzer-light - test 1\node_modules\.pnpm\drizzle-kit@0.30.6\node_modules\drizzle-kit\node_modules;E:\CV-analyzer-light - test 1\node_modules\.pnpm\drizzle-kit@0.30.6\node_modules;E:\CV-analyzer-light - test 1\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\drizzle-kit\bin.cjs" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\drizzle-kit\bin.cjs" %*
)
