import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {spawn} from 'node:child_process';
const cwd=mkdtempSync(join(tmpdir(),'cv-smoke-'));
const port=Number(process.env.TEST_PORT || 31873);
const child=spawn(process.execPath,[resolve('dist/server.mjs')],{cwd,env:{...process.env,PORT:String(port),NODE_ENV:'production',AUTH_SECRET:'isolated-smoke-test-secret'}});
try {
 await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('Startup timeout')),15000);child.stdout.on('data',d=>{if(d.toString().includes('Server listening')){clearTimeout(timer);ok();}});child.on('exit',c=>{clearTimeout(timer);fail(new Error('Server exited '+c));});child.stderr.on('data',d=>process.stderr.write(d));});
 const base=`http://127.0.0.1:${port}`;
 const login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'admin',password:'admin123'})});
 assert.equal(login.status,200);const cookie=login.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie);
 const call=async(path,method='GET',body)=>fetch(base+path,{method,headers:{Cookie:cookie,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
 assert.equal((await fetch(base)).status,200);
 assert.equal((await fetch(base+'/api/candidates/1/applications')).status,401);
 const body={title:'Network engineer',department:'IT',location:'Riyadh',experience:5,degree:'Bachelor',checklist:[],workflowType:'tender',projectName:'Synthetic project',requiredCount:3};
 const created=await call('/api/jobs','POST',body);assert.equal(created.status,201);const job=await created.json();assert.equal(job.workflowType,'tender');assert.equal(job.requiredCount,3);
 assert.equal((await call('/api/jobs','POST',{...body,requiredCount:-1})).status,400);
 assert.equal((await call('/api/screening-settings')).status,200);
 assert.equal((await (await call('/api/screening-settings')).json()).analysisMode,'local');
 assert.equal((await call('/api/jobs','POST',{...body,checklist:[{id:'x',requirement:'Certificate',ruleType:'certificate',acceptedTerms:[]}]})).status,400);
 const rules=[{id:'cert',requirement:'Certificate',importance:'Mandatory',ruleType:'certificate',acceptedTerms:['CSSA','CLSA']}];
 const ruled=await call('/api/jobs','POST',{...body,checklist:rules});assert.equal(ruled.status,201);
 assert.deepEqual(JSON.parse((await ruled.json()).checklist),rules);
 assert.equal((await call('/api/jobs/'+job.id,'PUT',{workflowType:'invalid'})).status,400);
 const updated=await (await call('/api/jobs/'+job.id,'PUT',{workflowType:'recruitment'})).json();assert.equal(updated.projectName,'Synthetic project');assert.equal(updated.workflowType,'recruitment');
 const db=new DatabaseSync(join(cwd,'sqlite.db'));
 const add=db.prepare('INSERT INTO candidates(job_id,name,match_score,file_hash) VALUES(?,?,?,?)');
 const a=Number(add.run(job.id,'Synthetic A',85,'same-document').lastInsertRowid);const b=Number(add.run(job.id,'Synthetic A',90,'same-document').lastInsertRowid);const c=Number(add.run(job.id,'Synthetic A',95,'different-document').lastInsertRowid);
 const apps=await (await call('/api/candidates/'+a+'/applications')).json();assert.deepEqual(apps.map(x=>x.id),[a,b]);assert.ok(!apps.some(x=>x.id===c));
 const identityPath=id=>'/api/candidates/'+id+'/identity';
 assert.equal((await fetch(base+identityPath(a))).status,401);
 const targetIdentity=await (await call(identityPath(a))).json();
 const sourceIdentity=await (await call(identityPath(c))).json();
 const link={sourceId:c,sourceVersion:sourceIdentity.version,version:targetIdentity.version,reason:'Synthetic identity verification'};
 assert.equal((await call(identityPath(a)+'/link','POST',{...link,reason:''})).status,400);
 db.prepare('INSERT INTO staffing_approvals(candidate_id,project_key,identity_key,revision,reviewer,approved_at) VALUES(?,?,?,?,?,?)').run(a,'test','ref','old','admin','now');
 assert.equal((await call(identityPath(a)+'/link','POST',link)).status,200);
 assert.equal(db.prepare('SELECT count(*) AS n FROM staffing_approvals WHERE candidate_id=?').get(a).n,0);
 assert.deepEqual((await (await call('/api/candidates/'+a+'/applications')).json()).map(x=>x.id),[a,b,c]);
 assert.equal((await call(identityPath(a)+'/link','POST',link)).status,409);
 const more=Number(add.run(job.id,'Synthetic A',92,'different-document').lastInsertRowid);
 let combined=await (await call(identityPath(a))).json();
 assert.deepEqual(combined.members.map(m=>m.id),[a,b,c,more]);
 assert.equal((await call(identityPath(a)+'/unlink','POST',{version:combined.version,profileId:999999,reason:'test'})).status,400);
 assert.equal((await call(identityPath(a)+'/unlink','POST',{version:combined.version,profileId:sourceIdentity.members[0].profileId,reason:'Separate verified person'})).status,200);
 assert.deepEqual((await (await call(identityPath(a))).json()).members.map(m=>m.id),[a,b]);
 assert.deepEqual((await (await call(identityPath(c))).json()).members.map(m=>m.id),[c,more]);
 assert.equal(db.prepare('SELECT file_hash FROM candidates WHERE id=?').get(c).file_hash,'different-document');
 assert.equal(db.prepare("SELECT count(*) AS n FROM audit_logs WHERE action_type IN ('Identity Link','Identity Unlink')").get().n,2);
 db.prepare('DELETE FROM candidates WHERE id=?').run(more);
 await call('/api/screening-settings','PUT',{matchThreshold:90});const stats=await (await call('/api/dashboard/stats')).json();assert.equal(stats.excellentMatches,2);
 const provider=await call('/api/ai-providers','POST',{providerName:'Google Gemini',modelName:'gemini-custom-test',apiKey:'synthetic-key-only',isCustomModel:true});
 assert.equal(provider.status,201);const providerId=(await provider.json()).id;
 assert.equal((await call('/api/ai-providers/'+providerId,'PUT',{modelName:'gemini-custom-updated',isCustomModel:true})).status,200);
 assert.equal(db.prepare('SELECT api_key FROM ai_providers WHERE id=?').get(providerId).api_key,'synthetic-key-only');
 assert.equal((await call('/api/ai-providers/'+providerId,'PUT',{modelName:'Gemini 3 Flash',isCustomModel:true})).status,400);
 // Review and staffing workflow: no provider calls or real candidate data.
 const tender=await (await call('/api/jobs','POST',{...body,requiredCount:1,checklist:rules})).json();
 const tender2=await (await call('/api/jobs','POST',{...body,title:'Second role',requiredCount:1,checklist:rules})).json();
 const first=Number(add.run(tender.id,'Synthetic Reviewer A',90,'review-cv-a').lastInsertRowid);
 const second=Number(add.run(tender2.id,'Synthetic Reviewer A',90,'review-cv-b').lastInsertRowid);
 const endpoint=id=>'/api/candidates/'+id+'/evidence-reviews';
 assert.equal((await fetch(base+endpoint(first))).status,401);
 const review=await (await call(endpoint(first))).json();
 assert.equal((await call('/api/candidates/'+first+'/staffing-approval','POST',{revision:review.revision,identityKey:'person-a'})).status,400);
 const payload={revision:review.revision,requirementId:'cert',status:'met',evidence:'Verified certificate',note:'Synthetic test review',page:1};
 assert.equal((await call(endpoint(first),'POST',{...payload,evidence:''})).status,400);
 assert.equal((await call(endpoint(first),'POST',payload)).status,201);
 assert.equal((await call('/api/candidates/'+first+'/staffing-approval','POST',{revision:review.revision,identityKey:'person-a'})).status,201);
 let coverage=await (await call('/api/project-coverage')).json();
 assert.equal(coverage.rows.find(r=>r.jobId===tender.id).shortage,0);
 const next=await (await call(endpoint(second))).json();
 assert.equal((await call(endpoint(second),'POST',{...payload,revision:next.revision})).status,201);
 assert.equal((await call('/api/candidates/'+second+'/staffing-approval','POST',{revision:next.revision,identityKey:' PERSON-A '})).status,409);
 const staffTarget=await (await call(identityPath(first))).json();
 const staffSource=await (await call(identityPath(second))).json();
 assert.equal((await call(identityPath(first)+'/link','POST',{version:staffTarget.version,sourceId:second,sourceVersion:staffSource.version,reason:'Verified two versions of the same person'})).status,200);
 assert.equal((await (await call('/api/candidates/'+first+'/evidence-reviews')).json()).approval,null);
 assert.equal((await call('/api/candidates/'+first+'/staffing-approval','POST',{revision:review.revision,identityKey:'person-a'})).status,201);
 assert.equal((await call('/api/candidates/'+second+'/staffing-approval','POST',{revision:next.revision,identityKey:'different-reference'})).status,409);
 await call('/api/jobs/'+tender.id,'PUT',{checklist:[{...rules[0],requirement:'Changed requirement'}]});
 assert.equal((await call(endpoint(first),'POST',payload)).status,409);
 coverage=await (await call('/api/project-coverage')).json();
 assert.equal(coverage.rows.find(r=>r.jobId===tender.id).shortage,1);
 assert.equal((await (await call(endpoint(first))).json()).history[0].stale,true);
 db.prepare('UPDATE candidates SET gdpr_anonymized=1 WHERE id=?').run(first);
 assert.equal(db.prepare('SELECT count(*) AS n FROM evidence_reviews WHERE candidate_id=?').get(first).n,0);
 assert.equal((await call(identityPath(first))).status,404);
 const visibleGroup=await (await call(identityPath(second))).json();
 assert.ok(!visibleGroup.members.some(m=>m.id===first));
 const identitySearch=await (await call('/api/identity-search?q=Synthetic')).json();
 assert.ok(!identitySearch.some(m=>m.id===first));
 assert.equal((await (await call('/api/identity-search?q=%25%25')).json()).length,0);
 const permission=db.prepare("SELECT * FROM role_capabilities WHERE role='admin' AND capability='change_status'").get();
 if(permission) db.prepare('UPDATE role_capabilities SET is_enabled=0 WHERE id=?').run(permission.id);
 else db.prepare("INSERT INTO role_capabilities(role,capability,is_enabled) VALUES('admin','change_status',0)").run();
 assert.equal((await call(endpoint(second),'POST',{...payload,revision:next.revision})).status,403);
 assert.equal((await call('/api/candidates/'+second+'/staffing-approval','POST',{revision:next.revision,identityKey:'person-b'})).status,403);
 assert.equal((await call('/api/candidates/'+second+'/staffing-approval','DELETE')).status,403);
 assert.equal((await call(identityPath(a)+'/link','POST',link)).status,403);
 assert.equal((await call(identityPath(a)+'/unlink','POST',{version:targetIdentity.version,profileId:targetIdentity.members[0].profileId,reason:'test'})).status,403);
 db.close();
 console.log('PASS: production frontend, auth, workflow CRUD/validation, conservative profile linking, configurable dashboard threshold.');
} finally {
 child.kill();await new Promise(r=>child.once('close',r));rmSync(cwd,{recursive:true,force:true});
}
